### ISSUE TITLE
Mamy Problema

### ISSUE THREAD

**Issue by Zealur** [Justa3122/RSS#1]
#ErrorTakieWazny

**Comment by Justa3122** [comment]
A czo to za error? My tu errorów nie robimy! :-1:

**Comment by Zealur** [comment]
jaka łapa w dół :( :rabbit:

**Comment by Zealur** [comment]
:rabbit: :rabbit:  króliczek się zawiódł

**Comment by Justa3122** [comment]
A zauważyłeś dziś mój nowy haircut? :haircut: :D

**Comment by Justa3122** [comment]
:rabbit2:  ten lepszy

**Comment by Zealur** [comment]
:+1: oczywiście masz like'a!  piona :hand:

**Comment by Justa3122** [comment]
Yeah, wiedziałam, że to była #GoodChoice i nie ma #2 źle :hand: :laughing:

**Comment by Zealur** [comment]
#GutCzojs #NajsŁanSista

**Comment by Justa3122** [comment]
#HajsSieMusiZgadzać ! :moneybag:

**Comment by Zealur** [comment]
:hankey: gówno prawda!

**Comment by Justa3122** [comment]
Two :man_with_gua_pi_mao:  one :hammer: haha
